"""
Configuration management for ACED-MARL training and evaluation.

Provides dataclasses for storing experiment configs and methods to load/save
configurations from/to YAML files.

Generated by copilot for load and save configurations.
"""

from dataclasses import dataclass, asdict, field
from typing import Dict, Any, Optional, List
from pathlib import Path
import yaml
import json


@dataclass
class EnvironmentConfig:
    """Configuration for the AcedPayloadEnv."""

    n_agents: int = 3
    arena_size: float = 25.0
    max_steps: int = 200
    event_driven: bool = True
    cooldown_time: int = 3
    contact_radius: float = 3.0
    goal_radius: float = 5.0
    goal_border_offset: float = 0.1
    placement_radius: float = 0.9
    max_agent_speed: float = 5.0
    broadcast_dim: int = 64

    # Robustness factors
    comm_dropout_prob: float = 0.0
    comm_delay_steps: int = 0
    sensor_dropout_prob: float = 0.0


@dataclass
class AgentConfig:
    """Configuration for agent architecture."""

    agent_type: str = "mappo"  # "mappo" or "mat"
    use_atoc: bool = False
    hidden_dim: int = 128
    broadcast_dim: int = 64
    broadcast_dim: int = 64

    # MAT-specific
    n_heads: int = 4
    n_layers: int = 2

    # CTDE
    use_centralized_critic: bool = True


@dataclass
class TrainingConfig:
    """Configuration for training."""

    num_workers: int = 4
    num_gpus: int = 0
    num_gpus_per_worker: float = 0.0

    # Training hyperparameters
    total_timesteps: int = 1_000_000
    rollout_fragment_length: int = 200
    train_batch_size: int = 4000
    sgd_minibatch_size: int = 128
    num_epochs: int = 20

    # Learning rates
    lr: float = 3e-4

    # PPO hyperparameters
    gamma: float = 0.99
    lambda_: float = 0.95
    clip_param: float = 0.2
    vf_loss_coeff: float = 0.5
    entropy_coeff: float = 0.01

    # Memory optimization
    use_gradient_accumulation: bool = False
    grad_accumulation_steps: int = 1
    use_memory_efficient_mode: bool = False


@dataclass
class CheckpointConfig:
    """Configuration for checkpointing."""

    checkpoint_frequency: int = 10
    checkpoint_at_end: bool = True
    keep_checkpoints_num: int = 3


@dataclass
class EvaluationConfig:
    """Configuration for evaluation."""

    n_episodes: int = 100

    # Robustness testing
    test_robustness: bool = False
    dropout_rates: List[float] = field(default_factory=lambda: [0.0, 0.2, 0.4, 0.6])
    delay_steps: List[int] = field(default_factory=lambda: [0, 5, 10, 20])
    sensor_dropout_rates: List[float] = field(default_factory=lambda: [0.0, 0.1, 0.2])


@dataclass
class ExperimentConfig:
    """Complete experiment configuration."""

    name: str = "default_experiment"
    description: str = ""

    # Sub-configurations
    environment: EnvironmentConfig = field(default_factory=EnvironmentConfig)
    agent: AgentConfig = field(default_factory=AgentConfig)
    training: TrainingConfig = field(default_factory=TrainingConfig)
    checkpoint: CheckpointConfig = field(default_factory=CheckpointConfig)
    evaluation: EvaluationConfig = field(default_factory=EvaluationConfig)

    # Output configuration
    output_dir: str = "results"
    seed: Optional[int] = None
    verbose: bool = True


class ConfigManager:
    """Manage experiment configurations."""

    @staticmethod
    def load_yaml(config_path: str) -> ExperimentConfig:
        """Load configuration from YAML file."""
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Config file not found: {config_path}")

        with open(path, "r") as f:
            config_dict = yaml.safe_load(f)

        return ConfigManager.from_dict(config_dict)

    @staticmethod
    def save_yaml(config: ExperimentConfig, output_path: str):
        """Save configuration to YAML file."""
        output_path_ = Path(output_path)
        output_path_.parent.mkdir(parents=True, exist_ok=True)

        config_dict = ConfigManager.to_dict(config)
        with open(output_path, "w") as f:
            yaml.dump(config_dict, f, default_flow_style=False, sort_keys=False)

    @staticmethod
    def from_dict(config_dict: Dict[str, Any]) -> ExperimentConfig:
        """Create ExperimentConfig from dictionary."""
        exp_config = ExperimentConfig()

        if "name" in config_dict:
            exp_config.name = config_dict["name"]
        if "description" in config_dict:
            exp_config.description = config_dict["description"]
        if "output_dir" in config_dict:
            exp_config.output_dir = config_dict["output_dir"]
        if "seed" in config_dict:
            exp_config.seed = config_dict["seed"]
        if "verbose" in config_dict:
            exp_config.verbose = config_dict["verbose"]

        if "environment" in config_dict:
            env_dict = config_dict["environment"]
            exp_config.environment = EnvironmentConfig(
                **{
                    k: v
                    for k, v in env_dict.items()
                    if k in EnvironmentConfig.__dataclass_fields__
                }
            )

        if "agent" in config_dict:
            agent_dict = config_dict["agent"]
            exp_config.agent = AgentConfig(
                **{
                    k: v
                    for k, v in agent_dict.items()
                    if k in AgentConfig.__dataclass_fields__
                }
            )

        if "training" in config_dict:
            train_dict = config_dict["training"]
            exp_config.training = TrainingConfig(
                **{
                    k: v
                    for k, v in train_dict.items()
                    if k in TrainingConfig.__dataclass_fields__
                }
            )

        if "checkpoint" in config_dict:
            ckpt_dict = config_dict["checkpoint"]
            exp_config.checkpoint = CheckpointConfig(
                **{
                    k: v
                    for k, v in ckpt_dict.items()
                    if k in CheckpointConfig.__dataclass_fields__
                }
            )

        if "evaluation" in config_dict:
            eval_dict = config_dict["evaluation"]
            exp_config.evaluation = EvaluationConfig(
                **{
                    k: v
                    for k, v in eval_dict.items()
                    if k in EvaluationConfig.__dataclass_fields__
                }
            )

        return exp_config

    @staticmethod
    def to_dict(config: ExperimentConfig) -> Dict[str, Any]:
        """Convert ExperimentConfig to dictionary."""
        return {
            "name": config.name,
            "description": config.description,
            "output_dir": config.output_dir,
            "seed": config.seed,
            "verbose": config.verbose,
            "environment": asdict(config.environment),
            "agent": asdict(config.agent),
            "training": asdict(config.training),
            "checkpoint": asdict(config.checkpoint),
            "evaluation": asdict(config.evaluation),
        }

    @staticmethod
    def save_json(config: ExperimentConfig, output_path: str):
        """Save configuration to JSON file."""
        output_path_ = Path(output_path)
        output_path_.parent.mkdir(parents=True, exist_ok=True)

        config_dict = ConfigManager.to_dict(config)
        with open(output_path, "w") as f:
            json.dump(config_dict, f, indent=2)

    @staticmethod
    def merge_configs(
        base: ExperimentConfig, overrides: Dict[str, Any]
    ) -> ExperimentConfig:
        """Merge override dictionary into base config."""
        config_dict = ConfigManager.to_dict(base)

        # Recursively merge overrides
        for key, value in overrides.items():
            if (
                isinstance(value, dict)
                and key in config_dict
                and isinstance(config_dict[key], dict)
            ):
                config_dict[key].update(value)
            else:
                config_dict[key] = value

        return ConfigManager.from_dict(config_dict)


def get_default_configs() -> Dict[str, ExperimentConfig]:
    """Return dictionary of pre-defined default configurations."""
    configs = {}

    # MAPPO Synchronous (baseline)
    configs["mappo_sync"] = ExperimentConfig(
        name="mappo_synchronous",
        description="MAPPO baseline in synchronous mode",
        environment=EnvironmentConfig(event_driven=False),
        agent=AgentConfig(agent_type="mappo", use_atoc=False),
        training=TrainingConfig(num_workers=4),
    )

    # MAPPO Event-driven
    configs["mappo_event"] = ExperimentConfig(
        name="mappo_event_driven",
        description="MAPPO baseline in event-driven mode",
        environment=EnvironmentConfig(event_driven=True),
        agent=AgentConfig(agent_type="mappo", use_atoc=False),
        training=TrainingConfig(num_workers=4),
    )

    # MAPPO + ATOC Synchronous
    configs["mappo_atoc_sync"] = ExperimentConfig(
        name="mappo_atoc_synchronous",
        description="MAPPO with ATOC in synchronous mode",
        environment=EnvironmentConfig(event_driven=False),
        agent=AgentConfig(agent_type="mappo", use_atoc=True),
        training=TrainingConfig(num_workers=4),
    )

    # MAPPO + ATOC Event-driven
    configs["mappo_atoc_event"] = ExperimentConfig(
        name="mappo_atoc_event_driven",
        description="MAPPO with ATOC in event-driven mode",
        environment=EnvironmentConfig(event_driven=True),
        agent=AgentConfig(agent_type="mappo", use_atoc=True),
        training=TrainingConfig(num_workers=4),
    )

    # MAT Synchronous
    configs["mat_sync"] = ExperimentConfig(
        name="mat_synchronous",
        description="MAT baseline in synchronous mode",
        environment=EnvironmentConfig(event_driven=False),
        agent=AgentConfig(agent_type="mat", use_atoc=False),
        training=TrainingConfig(num_workers=4),
    )

    # MAT Event-driven
    configs["mat_event"] = ExperimentConfig(
        name="mat_event_driven",
        description="MAT baseline in event-driven mode",
        environment=EnvironmentConfig(event_driven=True),
        agent=AgentConfig(agent_type="mat", use_atoc=False),
        training=TrainingConfig(num_workers=4),
    )

    # MAT + ATOC Synchronous
    configs["mat_atoc_sync"] = ExperimentConfig(
        name="mat_atoc_synchronous",
        description="MAT with ATOC in synchronous mode",
        environment=EnvironmentConfig(event_driven=False),
        agent=AgentConfig(agent_type="mat", use_atoc=True),
        training=TrainingConfig(num_workers=4),
    )

    # MAT + ATOC Event-driven
    configs["mat_atoc_event"] = ExperimentConfig(
        name="mat_atoc_event_driven",
        description="MAT with ATOC in event-driven mode",
        environment=EnvironmentConfig(event_driven=True),
        agent=AgentConfig(agent_type="mat", use_atoc=True),
        training=TrainingConfig(num_workers=4),
    )

    # Quick test (low memory)
    configs["quick_test"] = ExperimentConfig(
        name="quick_test",
        description="Quick test with low memory footprint",
        environment=EnvironmentConfig(n_agents=3, max_steps=100, event_driven=False),
        agent=AgentConfig(agent_type="mappo", use_atoc=False, hidden_dim=64),
        training=TrainingConfig(
            num_workers=1,
            total_timesteps=10_000,
            train_batch_size=1000,
            use_memory_efficient_mode=True,
        ),
    )

    return configs


if __name__ == "__main__":
    # Example: Create and save default configs
    from pathlib import Path

    configs = get_default_configs()
    config_dir = Path("configs")
    config_dir.mkdir(exist_ok=True)

    for name, config in configs.items():
        ConfigManager.save_yaml(config, f"configs/{name}.yaml")
        print(f"Saved configs/{name}.yaml")

    print(f"\nCreated {len(configs)} default configuration files")
