import math
import random
from typing import List, Tuple, Dict, Optional
from collections import deque

import gymnasium as gym
import numpy as np
import torch
from gymnasium import spaces
from pettingzoo import ParallelEnv
from config import EnvironmentConfig

from dataclasses import dataclass


# ---- generated by chatgpt when asking about encoding multiple actions into one -----------
def encode(actions: List[int], action_space: int = 6) -> int:
    """Encode a list of actions into a single integer."""
    # actions: list/tuple of int for each agent
    # A: size of each agent's action space
    joint = 0
    multiplier = 1
    for a in actions:
        joint += a * multiplier
        multiplier *= action_space
    return joint


def decode(joint: int, num_agents: int, action_space: int = 6) -> np.ndarray:
    """Decode a single integer into a list of actions."""
    actions = []
    for _ in range(num_agents):
        actions.append(joint % action_space)
        joint //= action_space
    return np.array(actions, dtype=int)


# ---- end of generated code


class BasePayloadEnv(gym.Env):
    """
    A simplified 2D multi-agent payload-transport environment with partial observability.

    - n_agents: number of rovers
    - step-based (synchronous) mode: all agents act every environment step
    - event-driven mode: agents have cooldowns; receiving messages triggers readiness

    Observation per agent (shape: (n_agents, obs_dim)):
    [vx, vy, dist_payload, dist_goal, msg_vx, msg_vy, msg_dist_payload, msg_dist_goal, msg_age, cooldown]

    Action space: MultiDiscrete([6]*n_agents)
     0: NOOP / hold
     1: +x velocity
     2: -x velocity
     3: +y velocity
     4: -y velocity
     5: update (broadcast velocity and beacon readings)

    Reward: progress of payload toward goal; bonus for reaching goal; penalty for losing contact.
    """

    metadata = {"render_modes": ["human"], "render_fps": 10}

    def __init__(
        self,
        config: EnvironmentConfig = None,
        n_agents: int = 3,
        arena_size: float = 20.0,
        goal_radius: float = 5.0,
        goal_border_offset: float = 0.1,
        max_steps: int = 200,
        event_driven: bool = False,
        cooldown_time: int = 0,
        contact_radius: float = 2.0,
        placement_radius: float = 0.9,
        max_agent_speed: float = 5.0,
        decay_factor: float = 0.9,
    ):
        super().__init__()
        self.n_agents = n_agents
        self.arena_size = arena_size
        self.goal_radius = goal_radius
        self.goal_border_offset = goal_border_offset
        self.max_steps = max_steps
        self.event_driven = event_driven
        self.cooldown_time = cooldown_time
        self.contact_radius = contact_radius
        self.placement_radius = placement_radius
        self.max_agent_speed = max_agent_speed
        self.decay_factor = decay_factor

        self.group_reward_weights = [
            5.0,  # r_dist
            5.0,  # r_contact
            -10.0,  # r_contact_fail
            100.0,  # r_success
        ]

        self.payload_reward = 5.0

        if config is not None:
            self.__dict__.update(config.__dict__)

        # observation: [vx, vy, dist_payload, dist_goal, cooldown]
        self.obs_dim = 5
        self.action_dim = 6
        # Use realistic bounds based on arena size and max speed
        # Velocities: [-max_speed*1.5, max_speed*1.5] for safety margin
        # Distances: [0, arena_size*sqrt(2)] for diagonal distance
        # Cooldown: [0, cooldown_time] upper bound
        max_distance = self.arena_size * math.sqrt(2)
        low = np.array(
            [
                [
                    -self.max_agent_speed * 1.5,
                    -self.max_agent_speed * 1.5,
                    0.0,
                    0.0,
                    0.0,
                ]
            ]
            * self.n_agents,
            dtype=np.float32,
        )
        high = np.array(
            [
                [
                    self.max_agent_speed * 1.5,
                    self.max_agent_speed * 1.5,
                    max_distance,
                    max_distance,
                    float(self.cooldown_time),
                ]
            ]
            * self.n_agents,
            dtype=np.float32,
        )
        self.observation_space = spaces.Box(low=low, high=high, dtype=np.float32)
        # actions per agent: 0..5
        self.action_space = spaces.MultiDiscrete([6] * self.n_agents)

        # internal state
        self.goal = np.zeros(2, dtype=float)
        self.agents_pos = np.zeros((self.n_agents, 2), dtype=float)
        self.agents_vel = np.zeros((self.n_agents, 2), dtype=float)
        self.payload_pos = np.array([arena_size / 2.0, arena_size / 2.0], dtype=float)
        self.payload_vel = np.zeros(2, dtype=float)
        self.step_count = 0

        # event-driven readiness / cooldown per agent
        self.cooldowns: list[int] = [0 for _ in range(self.n_agents)]

        # random seed
        self.seed()

    def seed(self, seed: Optional[int] = None):
        self._rng = np.random.default_rng(seed)
        random.seed(seed)

    def _place_goal(self, border_offset: float = 0.1):
        """Place goal randomly on arena border."""
        side = self._rng.integers(0, 4)
        match side:
            case 0:  # left
                self.goal = np.array(
                    [
                        self._rng.uniform(0.0, self.arena_size * border_offset),
                        self._rng.uniform(0.0, self.arena_size),
                    ],
                    dtype=float,
                )
            case 1:  # right
                self.goal = np.array(
                    [
                        self._rng.uniform(
                            self.arena_size * (1 - border_offset), self.arena_size
                        ),
                        self._rng.uniform(0.0, self.arena_size),
                    ],
                    dtype=float,
                )
            case 2:  # bottom
                self.goal = np.array(
                    [
                        self._rng.uniform(0.0, self.arena_size),
                        self._rng.uniform(0.0, self.arena_size * border_offset),
                    ],
                    dtype=float,
                )
            case 3:  # top
                self.goal = np.array(
                    [
                        self._rng.uniform(0.0, self.arena_size),
                        self._rng.uniform(
                            self.arena_size * (1 - border_offset), self.arena_size
                        ),
                    ],
                    dtype=float,
                )
            case _:
                self.goal = np.array(
                    [self.arena_size, self.arena_size / 2.0], dtype=float
                )

    def _place_payload(self, offset: float = 0.2):
        """Place payload near center with agents in contact range."""
        self.payload_pos = np.array(
            [
                self.arena_size / 2.0
                + self._rng.uniform(
                    -self.arena_size * offset, self.arena_size * offset
                ),
                self.arena_size / 2.0
                + self._rng.uniform(
                    -self.arena_size * offset, self.arena_size * offset
                ),
            ],
            dtype=float,
        )
        self.payload_vel = np.zeros(2)

        # Initialize agents within contact radius
        for i in range(self.n_agents):
            angle = self._rng.uniform(0.0, 2.0 * math.pi)
            r = self._rng.uniform(0.0, self.contact_radius * self.placement_radius)
            offset_vec = np.array([math.cos(angle) * r, math.sin(angle) * r])
            pos = self.payload_pos + offset_vec
            self.agents_pos[i] = np.clip(pos, 0.0, self.arena_size)
            self.agents_vel[i] = np.zeros(2)

    def reset(
        self, *, seed: Optional[int] = None, options: Optional[dict] = None
    ) -> Tuple[np.ndarray, Dict]:
        """Reset the environment and return the initial observation."""
        if seed is not None:
            self.seed(seed)

        self._place_goal()
        self._place_payload()
        self.step_count = 0
        self.cooldowns = [0 for _ in range(self.n_agents)]
        self.total_contact_time = [0 for _ in range(self.n_agents)]

        obs = self._get_obs()
        return obs, {}

    def _get_obs(self) -> np.ndarray:
        """
        Observation per agent (partial observability):
        [vx, vy, dist_payload, dist_goal, cooldown, broadcasts]
        """
        obs = np.zeros((self.n_agents, self.obs_dim), dtype=np.float32)
        for i in range(self.n_agents):
            vx, vy = self.agents_vel[i]
            dist_payload = np.linalg.norm(self.payload_pos - self.agents_pos[i])
            dist_goal = np.linalg.norm(self.goal - self.agents_pos[i])

            cd = float(self.cooldowns[i])
            obs[i] = np.array(
                [
                    vx,
                    vy,
                    dist_payload,
                    dist_goal,
                    cd,
                ],
                dtype=np.float32,
            )
        # Ensure observations are float32 (Gym expects float32 by default)
        return obs.astype(np.float32, copy=False)

    def _reward(self) -> np.ndarray:
        """Compute reward based on environment state and info."""
        dist_to_goal = np.linalg.norm(self.goal - self.payload_pos)

        agents_in_contact = (
            np.linalg.norm(self.agents_pos - self.payload_pos, axis=1)
            <= self.contact_radius
        )
        agents_contacting = agents_in_contact.sum()

        group_rewards = [
            1 - dist_to_goal / self.arena_size,  # r_dist
            agents_contacting / self.n_agents,  # r_contact
            agents_contacting < 2,  # r_contact_fail
            dist_to_goal < self.goal_radius,  # r_success
        ]

        rewards = np.full(
            self.n_agents,
            np.dot(self.group_reward_weights, group_rewards),
            dtype=np.float32,
        )

        # add reward to agents that are in contact with the payload
        rewards[agents_in_contact] += self.payload_reward
        rewards *= self.decay_factor ** (self.step_count / self.max_steps)
        return rewards

    def step(self, action: int) -> Tuple[np.ndarray, float, bool, bool, Dict]:
        """Execute one environment step."""
        self.step_count += 1

        actions = decode(action, self.n_agents, self.action_dim)
        if actions.shape[0] != self.n_agents:
            raise ValueError(
                f"actions must be length n_agents={self.n_agents}, got {actions.shape[0]}"
            )

        # Apply actions
        for i in range(self.n_agents):
            a = int(actions[i])
            if self.event_driven and self.cooldowns[i] > 0:
                a = 0  # NOOP if on cooldown

            if a == 0:
                pass  # hold
            elif a == 1:
                self.agents_vel[i][0] += 1.0
                self.cooldowns[i] = self.cooldown_time
            elif a == 2:
                self.agents_vel[i][0] -= 1.0
                self.cooldowns[i] = self.cooldown_time
            elif a == 3:
                self.agents_vel[i][1] += 1.0
                self.cooldowns[i] = self.cooldown_time
            elif a == 4:
                self.agents_vel[i][1] -= 1.0
                self.cooldowns[i] = self.cooldown_time
            elif a == 5:
                # Broadcasting agent enters cooldown
                self.cooldowns[i] = self.cooldown_time

        # Physics: clamp velocities BEFORE updating positions
        for i in range(self.n_agents):
            speed = np.linalg.norm(self.agents_vel[i])
            if speed > self.max_agent_speed:
                self.agents_vel[i] = (self.agents_vel[i] / speed) * self.max_agent_speed

        # Update agent positions
        for i in range(self.n_agents):
            self.agents_pos[i] += self.agents_vel[i] * 0.1
            self.agents_pos[i] = np.clip(self.agents_pos[i], 0.0, self.arena_size)

        # Payload physics: only agents in contact affect it
        distances = np.linalg.norm(self.agents_pos - self.payload_pos, axis=1)
        agents_in_contact = distances <= self.contact_radius

        # Track contact time
        for i in range(self.n_agents):
            if agents_in_contact[i]:
                self.total_contact_time[i] += 1

        self.payload_vel = np.mean(self.agents_vel[agents_in_contact], axis=0)
        self.payload_pos += self.payload_vel
        self.payload_pos = np.clip(self.payload_pos, 0.0, self.arena_size)

        # Decay cooldowns
        for i in range(self.n_agents):
            if self.cooldowns[i] > 0:
                self.cooldowns[i] = max(0, self.cooldowns[i] - 1)

        # Compute rewards
        dist_to_goal_after = float(np.linalg.norm(self.goal - self.payload_pos))
        contact_fraction = agents_in_contact.sum() / self.n_agents
        # Check termination conditions
        reached_goal = dist_to_goal_after < self.goal_radius
        dropped_contact = contact_fraction < 0.5
        max_steps_reached = self.step_count >= self.max_steps
        done: bool = reached_goal or dropped_contact or max_steps_reached
        success = reached_goal and not dropped_contact
        rewards = self._reward()

        # Compute metrics
        contact_fractions = [
            self.total_contact_time[i] / self.step_count for i in range(self.n_agents)
        ]

        info = {
            "success": success,
            "contact_fraction": contact_fraction,
            "avg_contact_fraction": np.mean(contact_fractions),
            "dist_to_goal": dist_to_goal_after,
            "individual_rewards": rewards.copy(),  # Store individual rewards for reference
        }

        # Return mean reward as single float value
        mean_reward = float(np.mean(rewards))
        return self._get_obs(), mean_reward, done, False, info

    def render(self, mode: str = "human"):
        """ASCII render of environment state."""
        grid = np.full((int(self.arena_size), int(self.arena_size)), ".", dtype=str)
        px, py = int(self.payload_pos[0]), int(self.payload_pos[1])
        gx_f, gy_f = float(self.goal[0]), float(self.goal[1])
        gx, gy = int(gx_f), int(gy_f)

        # Mark goal region
        for y in range(grid.shape[0]):
            for x in range(grid.shape[1]):
                if math.hypot(float(x) - gx_f, float(y) - gy_f) <= self.goal_radius:
                    grid[y, x] = "g"

        # Mark payload contact region
        for y in range(grid.shape[0]):
            for x in range(grid.shape[1]):
                if math.hypot(float(x) - px, float(y) - py) <= self.contact_radius:
                    grid[y, x] = "p"

        # Mark centers
        grid[gy, gx] = "G"
        grid[py, px] = "P"

        # Mark agents
        for i in range(self.n_agents):
            x, y = int(self.agents_pos[i][0]), int(self.agents_pos[i][1])
            if 0 <= x < grid.shape[1] and 0 <= y < grid.shape[0]:
                grid[y, x] = str(i % 10)

        out = "\n".join("".join(row) for row in grid[::-1])
        print(out)
        print(f"Distance to goal: {np.linalg.norm(self.payload_pos - self.goal):.2f}")
        print(f"Step: {self.step_count}\n")


class Broadcast:

    def __init__(
        self,
        message: Optional[np.ndarray] = None,
        delay: int = 0,
        broadcast_dim: int = 64,
    ):
        self.message_len = broadcast_dim
        self.message = (
            np.zeros(self.message_len, dtype=np.float32)
            if message is None
            else np.asarray(message, dtype=np.float32).reshape(-1)[: self.message_len]
        )
        if self.message.shape[0] < self.message_len:
            self.message = np.pad(
                self.message,
                (0, self.message_len - self.message.shape[0]),
                mode="constant",
            )
        self.delay = delay
        self.age = 0
        self.limit = delay * 2

    def get_message(self) -> np.ndarray:
        # message len is de
        return self.message if self.age >= self.delay else np.zeros(self.message_len)

    def update(self, message, delay: int = 0):
        self.age += 1
        if (message is not None) or (self.age >= self.limit):
            msg = np.asarray(message, dtype=np.float32).reshape(-1)
            if msg.shape[0] < self.message_len:
                msg = np.pad(msg, (0, self.message_len - msg.shape[0]), mode="constant")
            elif msg.shape[0] > self.message_len:
                msg = msg[: self.message_len]
            self.message = msg
            self.delay = delay
            self.age = 0
            self.limit = delay * 2


class BroadcastBuffer:
    def __init__(self, delay: int = 0, broadcast_dim: int = 64):
        self.delay = delay
        self.broadcast_dim = broadcast_dim
        self.buffer: dict[str, Broadcast] = {}

    def store_broadcast(self, message, agent_id: str, delay: int = 0):
        delay = max(delay, self.delay)
        self.buffer[agent_id] = Broadcast(
            message, delay, broadcast_dim=self.broadcast_dim
        )
        self.buffer[agent_id].update(message, delay)

    def get_broadcasts(self, agent_id: str) -> List[np.ndarray]:
        # Return messages from all *other* agents in deterministic key order
        return [
            self.buffer[k].get_message()
            for k in sorted(self.buffer.keys())
            if k != agent_id
        ]


class PettingZooPayloadEnv(ParallelEnv):
    """
    PettingZoo wrapper for your environment.
    This is the STANDARD way to do MARL - PettingZoo for environments,
    RLlib/MARLlib for training.
    """

    metadata = {"name": "aced_payload_v0", "render_modes": ["human"]}

    def __init__(
        self, config: EnvironmentConfig = None, broadcast_dim: Optional[int] = None
    ):
        self.env = BasePayloadEnv(config)
        self.n_agents = self.env.n_agents

        # Broadcast vector length (can be overridden or read from config)
        self.broadcast_dim = (
            broadcast_dim
            if broadcast_dim is not None
            else getattr(config, "broadcast_dim", 64) if config is not None else 64
        )

        # Each agent observes the base env features plus one broadcast vector
        # from every other agent (n_agents - 1).
        self.base_obs_dim = self.env.obs_dim
        self.obs_dim = (
            self.base_obs_dim + max(self.n_agents - 1, 0) * self.broadcast_dim
        )
        self.action_dim = self.env.action_dim

        # PettingZoo required attributes
        self.possible_agents = [f"agent_{i}" for i in range(self.n_agents)]
        self.agents = self.possible_agents[:]

        # Broadcast buffer for ATOC communication
        # Stores broadcasts generated by each agent for others to read
        self.broadcast_buffer: BroadcastBuffer = BroadcastBuffer(
            broadcast_dim=self.broadcast_dim
        )

        # Define spaces per agent - include base env obs plus (n_agents-1) broadcast slots.
        env_obs_low = self.env.observation_space.low[0]  # (obs_dim,)
        env_obs_high = self.env.observation_space.high[0]
        broadcast_low = np.zeros(
            self.broadcast_dim * max(self.n_agents - 1, 0), dtype=np.float32
        )
        broadcast_high = np.ones_like(broadcast_low, dtype=np.float32)

        obs_low = np.concatenate([env_obs_low, broadcast_low]).astype(np.float32)
        obs_high = np.concatenate([env_obs_high, broadcast_high]).astype(np.float32)

        self.observation_spaces = {
            agent: spaces.Box(low=obs_low, high=obs_high, dtype=np.float32)
            for agent in self.possible_agents
        }
        self.action_spaces = {
            agent: spaces.Discrete(self.action_dim) for agent in self.possible_agents
        }

    def reset(self, seed=None, options=None):
        """Reset and return {agent: obs} dict."""
        obs, _ = self.env.reset(seed=seed, options=options)
        self.agents = self.possible_agents[:]

        # Reset broadcast buffer
        self.broadcast_buffer = BroadcastBuffer(broadcast_dim=self.broadcast_dim)

        observations = {
            f"agent_{i}": np.concatenate(
                [
                    obs[i],
                    np.zeros(
                        self.broadcast_dim * max(self.n_agents - 1, 0),
                        dtype=np.float32,
                    ),
                ],
                dtype=np.float32,
            )
            for i in range(len(self.agents))
        }
        infos = {agent: {} for agent in self.agents}

        return observations, infos

    def step(self, actions: dict) -> Tuple[Dict, Dict, Dict, Dict, Dict]:
        """Step with {agent: action} dict.

        Handles:
        - Converting per-agent actions to environment array format
        - Masking invalid actions (e.g., broadcast when on cooldown in event-driven mode)
        - Sharing broadcasts through the broadcast buffer
        """

        # RLlib may pass plain ints/ndarrays per agent or dicts with an "action" key.
        def _get_agent_action(a):
            if isinstance(a, dict) and "action" in a:
                return a["action"]
            return a

        action_array = []
        for i in range(len(self.agents)):
            agent_key = f"agent_{i}"
            raw = actions.get(agent_key, 0)
            act = int(_get_agent_action(raw))
            if self.env.event_driven and self.env.cooldowns[i] > 0:
                act = 0
            action_array.append(act)

        # Encode joint action into single integer for base env
        encoded_action = encode(action_array, self.action_dim)

        obs, _, done, truncated, info = self.env.step(encoded_action)

        # Convert to PettingZoo format
        rewards = {
            f"agent_{i}": float(info["individual_rewards"][i])
            for i in range(len(self.agents))
        }
        terminations = {f"agent_{i}": done for i in range(len(self.agents))}
        truncations = {f"agent_{i}": truncated for i in range(len(self.agents))}
        # Copy base info per agent to avoid shared dict mutations
        infos = {f"agent_{i}": dict(info) for i in range(len(self.agents))}

        # Include communication context to observations
        # store broadcasts from agents that selected action 5
        for i, agent_id in enumerate([f"agent_{i}" for i in range(len(self.agents))]):
            # Optional broadcast field only when action==5 and provided
            raw_broadcast = np.zeros(self.broadcast_dim, dtype=np.float32)
            if action_array[i] == 5:
                maybe = actions.get(agent_id)
                if isinstance(maybe, dict) and "broadcast" in maybe:
                    raw_broadcast = maybe["broadcast"]
            # Normalize broadcast to a flat numpy array
            if isinstance(raw_broadcast, torch.Tensor):
                broadcast_np = raw_broadcast.detach().cpu().numpy().astype(np.float32)
            else:
                broadcast_np = np.asarray(raw_broadcast, dtype=np.float32)
            broadcast_np = broadcast_np.reshape(-1)  # ensure 1D
            if broadcast_np.size < self.broadcast_dim:
                broadcast_np = np.pad(
                    broadcast_np,
                    (0, self.broadcast_dim - broadcast_np.size),
                    mode="constant",
                )
            elif broadcast_np.size > self.broadcast_dim:
                broadcast_np = broadcast_np[: self.broadcast_dim]
            self.broadcast_buffer.store_broadcast(broadcast_np, agent_id)

        return self._obs(), rewards, terminations, truncations, infos

    def state(self) -> np.ndarray:
        """Get the current state of the environment."""
        return self.env._get_obs()

    def render(self) -> None:
        """Render the environment."""
        self.env.render()


def _make_parallel_pettingzoo_env(base_config: dict):
    """Return a callable suitable for RLlib that creates an AcedPayloadPettingZoo environment.

    RLlib sometimes passes an EnvContext when instantiating envs. To avoid confusion
    between the EnvContext and the PettingZoo env instance, we build a factory that
    always returns an `AcedPayloadPettingZoo` directly (no wrapper).
    """

    def _creator(env_context=None):
        # Merge base_config with any runtime context (env_context may be an EnvContext)
        cfg = dict(base_config or {})
        try:
            # If env_context behaves like a dict, merge its items
            cfg.update(dict(env_context or {}))
        except Exception:
            # env_context may be an EnvContext; ignore merging in that case
            pass
        # Wrap PettingZoo parallel env with RLlib's ParallelPettingZooEnv to satisfy Gymnasium API expectations
        from ray.rllib.env.wrappers.pettingzoo_env import ParallelPettingZooEnv

        return ParallelPettingZooEnv(PettingZooPayloadEnv(EnvironmentConfig(**cfg)))

    return _creator


def register_and_get_env_name(base_config: dict) -> str:
    """Register the PettingZoo environment factory and return its registered name.

    This avoids RLlib stringifying the function object, which was causing ugly trial names.
    """
    from ray.tune import register_env

    env_name = "aced_payload_pettingzoo_v0"
    env_factory = _make_parallel_pettingzoo_env(base_config)

    try:
        # Register (if already registered, this is a no-op)
        register_env(env_name, env_factory)
    except Exception:
        # Already registered or other issue; continue
        pass

    return env_name


def create_per_agent_multiagent_config(
    n_agents: int, obs_space, act_space, model_class, model_config: dict = {}
):
    """
    Create per-agent multiagent configuration for RLlib.

    Each agent gets its own policy instance, allowing them to learn independently
    while using the same network architecture.

    Args:
        n_agents: Number of agents
        obs_space: Observation space
        act_space: Action space
        model_class: Model class name (string) or class (if pre-registered)
        model_config: Optional model config dict

    Returns:
        Dictionary with multiagent configuration
    """
    model_config = model_config or {}

    # Create one policy per agent
    policies = {
        f"agent_{i}": (
            model_class,
            obs_space,
            act_space,
            {"custom_model_config": {**model_config, "agent_id": i}},
        )
        for i in range(n_agents)
    }

    # Map each agent to its policy
    policy_mapping_fn = lambda agent_id, episode, **kwargs: agent_id

    return {
        "policies": policies,
        "policy_mapping_fn": policy_mapping_fn,
    }
